[package]
name = "calc"
version = "0.1.4"
edition = "2021"
authors = ["Mike Lloyd"]

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
eval = "0.4.3"
regex = "1.5.4"
rink-core = "0.6.2"
